#pragma config(Sensor, S1, sGyro, sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2, sRight, sensorEV3_Ultrasonic)
#pragma config(Sensor, S3, sLight, sensorI2CCustom)
#pragma config(Sensor, S4, sLeft, sensorEV3_Ultrasonic)
#pragma config(Motor, motorA, mRight, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorB, mLeft, tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef MAIN_C
#define MAIN_C

#include "arbiter.c"

task main() {
    startTask(arbiter);
    while (!getButtonPress(buttonRight));
}

#endif MAIN_C
